package com.myrestaurant.app;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.myrestaurant.app.model.DishService;
import com.myrestaurant.app.ui.BaseForm;
import com.myrestaurant.app.ui.MainMenuForm;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyRestaurant {
    public static final String SERVER_URL = "http://localhost:8080/";
    //public static final String SERVER_URL = "http://10.0.1.4:8080/";
    public static final String APP_AUTH = "97adbd16-79a6-4e24-b516-d7361a2bab98";
    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        Toolbar.setGlobalToolbar(true);

        DishService.updateDishesFromServerAsync();
        
        // Pro only feature, uncomment if you have a pro subscription
        Log.bindCrashProtection(true);
        
        if(Display.getInstance().isTablet()) {
            Toolbar.setPermanentSideMenu(true);
        }
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        BaseForm.showMainMenuForm();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
